<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527160120 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial banking schema + append-only (immutable) audit_logs guard';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE accounts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, account_number VARCHAR(34) NOT NULL, currency VARCHAR(3) NOT NULL, balance_cents BIGINT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CAC89EACA76ED395 ON accounts (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_accounts_number ON accounts (account_number)');
        $this->addSql('CREATE TABLE audit_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, actor_user_id INT DEFAULT NULL, actor_email VARCHAR(180) DEFAULT NULL, event_type VARCHAR(64) NOT NULL, entity_type VARCHAR(64) DEFAULT NULL, entity_id VARCHAR(64) DEFAULT NULL, ip_address VARCHAR(64) DEFAULT NULL, user_agent VARCHAR(512) DEFAULT NULL, metadata JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_event_type ON audit_logs (event_type)');
        $this->addSql('CREATE INDEX idx_audit_created_at ON audit_logs (created_at)');
        $this->addSql('CREATE TABLE mfa_challenges (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, purpose VARCHAR(32) NOT NULL, related_transaction_id INT DEFAULT NULL, code_hash VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, attempts SMALLINT NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F8044525A76ED395 ON mfa_challenges (user_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, recipient VARCHAR(255) NOT NULL, message TEXT NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3A76ED395 ON notifications (user_id)');
        $this->addSql('CREATE TABLE transactions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recipient_name VARCHAR(255) NOT NULL, recipient_account VARCHAR(34) NOT NULL, amount_cents BIGINT NOT NULL, currency VARCHAR(3) NOT NULL, status VARCHAR(20) NOT NULL, risk_status VARCHAR(20) NOT NULL, risk_reason VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, source_account_id INT NOT NULL, created_by_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EAA81A4CE7DF2E9E ON transactions (source_account_id)');
        $this->addSql('CREATE INDEX IDX_EAA81A4C7D182D95 ON transactions (created_by_user_id)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, roles JSON NOT NULL, full_name VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_users_email ON users (email)');
        $this->addSql('ALTER TABLE accounts ADD CONSTRAINT FK_CAC89EACA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mfa_challenges ADD CONSTRAINT FK_F8044525A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4CE7DF2E9E FOREIGN KEY (source_account_id) REFERENCES accounts (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4C7D182D95 FOREIGN KEY (created_by_user_id) REFERENCES users (id) NOT DEFERRABLE');

        // SSDLC: the audit log must be immutable. Enforce append-only at the database level
        // so even a compromised application (or operator) cannot tamper with history.
        $this->addSql(<<<'SQL'
            CREATE OR REPLACE FUNCTION prevent_audit_log_mutation() RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_logs is append-only: % is not permitted', TG_OP;
            END;
            $$ LANGUAGE plpgsql;
            SQL);
        $this->addSql('CREATE TRIGGER audit_logs_no_update BEFORE UPDATE ON audit_logs FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation()');
        $this->addSql('CREATE TRIGGER audit_logs_no_delete BEFORE DELETE ON audit_logs FOR EACH ROW EXECUTE FUNCTION prevent_audit_log_mutation()');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TRIGGER IF EXISTS audit_logs_no_update ON audit_logs');
        $this->addSql('DROP TRIGGER IF EXISTS audit_logs_no_delete ON audit_logs');
        $this->addSql('DROP FUNCTION IF EXISTS prevent_audit_log_mutation()');
        $this->addSql('ALTER TABLE accounts DROP CONSTRAINT FK_CAC89EACA76ED395');
        $this->addSql('ALTER TABLE mfa_challenges DROP CONSTRAINT FK_F8044525A76ED395');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE transactions DROP CONSTRAINT FK_EAA81A4CE7DF2E9E');
        $this->addSql('ALTER TABLE transactions DROP CONSTRAINT FK_EAA81A4C7D182D95');
        $this->addSql('DROP TABLE accounts');
        $this->addSql('DROP TABLE audit_logs');
        $this->addSql('DROP TABLE mfa_challenges');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE transactions');
        $this->addSql('DROP TABLE users');
    }
}
